### ISSUE TITLE
Add option to open Talk window in tray context menu and by double click

### ISSUE THREAD

**Issue by e-alfred** [fds2610/NCT-Desktop#11] opened 2020-05-06 18:54 UTC
Hello,

please add an option to the tray menu to open the Talk window and/or by double clicking on the tray symbol. Currently the app can only be opened if a notification comes in.

**Comment by fds2610** [comment] 2020-05-08 06:40
will add:
- double-click icon and
- additional menu-entry (open NC window)

both will open either last sent link in NC notifications or - if none present - root NC path as configured in settings.

**Comment by fds2610** [comment] 2020-05-08 11:42
check new version if it addresses you needs...

**Comment by Refhi** [comment] 2020-05-12 12:44
a few bugs when I click the notification window wich appear a few seconds :
it does open a "talk" windows but :
- the "write" space to answer can't be accessed in the windows named "NCT Notifier" :
![Annotation 2020-05-12 143505](https://user-images.githubusercontent.com/2778215/81691907-e39fee00-945d-11ea-98fd-9473e72406ee.png)
- the menu in the window is not really working (ex. File => Exit) does nothing
- the window cannot be scaled (well, the window can, but not the content)
- when the window is closed with the cross, it seems to "keep the focus" : no more notifications are send when new lines of conversation are made until I restart NCT-notifier
- the first opening took a long time (could'nt reproduce the issue so I'm not sure)

=> may I Suggest that instead of opening that moderatly fonctionning electron window instead it opens the link in the defaut windows browser ? Or maybe add the option to choose between ?

thanks for your work ! I like where it's going !

**Comment by fds2610** [comment] 2020-05-13 09:44
Hi @Refhi i agree with you that opening the link in default browser should solve your issues. So i implemented in in 0.0.9. unfortunately it seems to be a known problem by the used electron libraries that the browser window-tab MAY open in background. please review current state if possible. I updated Win/Lin/Mac binaries also.

**Comment by Refhi** [comment] 2020-05-13 14:43
Hi @fds2610 just tried 0.09 on ubuntu, when clicking on the notification (whether on the popup or the notification tray) don't seems to lead to any result.

Moreover the last notification seems to pop every 10 second on a loop.

Here's the console log 

`linux
Sub: test
Msg: test2
Link: 
No more data in response.
PollOnce end
Sub: test
Msg: test2
Link: 
Clicked the Notification...
Trayicon re-set. 
cat: sortie standard: Mauvais descripteur de fichier
/usr/bin/xdg-open: 230: echo: echo: I/O error
Sub: test
Msg: test2
Link: 
`

I'll try on windows when I can

**Comment by fds2610** [comment] 2020-05-14 07:52
Die Meldungen:
cat: sortie standard: Mauvais descripteur de fichier
/usr/bin/xdg-open: 230: echo: echo: I/O error
heissen übersetzt
cat: Standardausgabe: Ungültiger Dateideskriptor
/usr/bin/xdg-open: 230: echo: echo: I/O error

heisst für mich, dass electron Deinen Standard-Browser nicht findet!? und es mit cat versucht!?

das mit dem 10-Sek-Popup stört mich auch etwas - muss ich wohl wieder rausmachen. Blöd ist, dass die verschiedenen Plattformen hier unterschiedlich reagieren. Win10 filtert das wohl besser / anders raus.

**Comment by Refhi** [comment] 2020-05-20 14:09
so a few tests :
- windows 10
- NCT-desktop 0.09
talk notification :
- if .occ notification, when clicked open file browser on home page (!) so startling but harmless
- if talk notification, when clicked open default web browser on the right page (talk page) excellent !

BUT whatever the origin of the notification it keeps poping every few seconds for as long as the notification isn't deleted in the web interface. 😢

**Comment by fds2610** [comment] 2020-05-29 11:52
ok, so just uploading 0.1.0 wher this should be fixed. please test, @Refhi !

**Comment by Refhi** [comment] 2020-06-01 13:20
ok so this time tested on ubuntu LTS 20.04 nct-desktop 0.1.0
When click "talk" notification on the popup => opens electron browser on the proper place but SLOWWWWWWWW on the first opening and the write space shows and usable.
BUT it does not show the messages and I can't send messages
![Capture d’écran du 2020-06-01 15-12-33](https://user-images.githubusercontent.com/2778215/83412521-7d820780-a41a-11ea-9b05-3466ea4dbb45.png)

Further notifications shows properly 
When I click "open NC in browser" in the tray context menu after a talk notification same behavior
(fast to open this time but still no messages)

When I click "open NC in browser" it seems to keep sending to the last notification origin, even when the notification is not shown anymore (good I guess but undocumented ?)

Clicking an .occ notification just open an electron blank window (no link showing in the terminal where I started nctdesktop unlike when cliking "talk" notification)
=> maybe a least make a defaut url to send to the nc home when no link is implied in the notification ? Or keep the last proper link ?

thanks for your work !

**Comment by Baccanno** [comment] 2020-06-03 10:42
> Hi @Refhi i agree with you that opening the link in default browser should solve your issues. So i implemented it in 0.0.9.
> Unfortunately it seems to be a known problem by the used electron libraries that the browser window-tab MAY open in background. please review current state if possible. I updated Win/Lin/Mac binaries also.

In the end the NCT-notifier opens and not my default browser. Should this still be the expected behaviour ? Because the NCT-notifier own window has some problems and can't be used to chat (stuck in various states, UI not responding, ect)

**Comment by fds2610** [comment] 2020-06-04 08:52
Hi @Baccanno, no this not intended. I accidently broke the already built in opening of an external browser with my new login-flow as I maintain only one binary currently. I will add another issue to implement a configurable version where either internal or default browser can be opened.
for me (W10+FF) it works best, if I log out from NC in any browser, then configure NCT-Desktop, and then login back into NC in my browser. all new notofications are being opened correctly.

**Comment by Baccanno** [comment] 2020-06-04 10:10
> Hi @Baccanno, no this not intended. I accidently broke the already built in opening of an external browser with my new login-flow as I maintain only one binary currently. I will add another issue to implement a configurable version where either internal or default browser can be opened.
> for me (W10+FF) it works best, if I log out from NC in any browser, then configure NCT-Desktop, and then login back into NC in my browser. all new notofications are being opened correctly.

This operation surprisingly worked. 1. I disconnected from Brave, 2. then went through configuration again 3. and now double clicking / "Open NC in browser" opens my default browser.

**Comment by fds2610** [comment] 2020-06-05 08:40
well i implemented this issue much better in 0.1.1 Beta ( #19  branch) , please test. All binaires are uploaded and ready for testing.

**Comment by fds2610** [comment] 2020-06-08 10:43
as this option is well tested now i close this issue.

**Closed by fds2610** 2020-06-08 10:43 UTC
Labels: enhancement, proposed solution
